name: Gradle CI & Tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 24
      uses: actions/setup-java@v2
      with:
        java-version: '24'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: Build
      run: ./gradlew build
    - name: Test and generate coverage information
      run: ./gradlew coverage
    - name: Upload coverage information to codecov
      uses: codecov/codecov-action@v2
      with:
        files: build/jcc-report/test/jacocoTestReport.xml
        name: sof-coverage-upload
        fail_ci_if_error: false
        verbose: true
