name: Gradle CI & Tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 24
      uses: actions/setup-java@v2
      with:
        java-version: '24'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
    - name: Test and generate coverage information
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: coverage
    - name: Upload coverage information to codecov
      uses: codecov/codecov-action@v2
      with:
        files: build/jcc-report/test/jacocoTestReport.xml
        name: sof-coverage-upload
        fail_ci_if_error: false
        verbose: true
